name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
        #step 1: Set up Python environment
      - name: Check out code
        uses: actions/checkout@v3
        #step 2: Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
        #step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        #step 4: Run tests
      - name: Run tests
        run: pytest

#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python 3.10
#         uses: actions/setup-python@v3
#         with:
#           python-version: "3.10"

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install flake8 pytest
#           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

#       - name: Lint with flake8
#         run: |
#           # stop the build on syntax errors
#           flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#           # exit-zero treats all errors as warnings
#           flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

#       - name: Test with pytest
#         run: pytest
